version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: mydatabase
    ports:
      - '3306:3306'
    networks:
      - mynetwork

  graphql-server:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - '4000:4000'
    networks:
      - mynetwork

  nextjs-server:
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - graphql-server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
